extends:
  - '@travi'
  - '@travi/mocha'
  - '@travi/cucumber'

overrides:
  - files: example/**/*.js
    extends: '@travi/react'
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
      react/prop-types: off
      no-undef: off
  - files:
    - src/**/*.js
    - test/unit/**/*-test.js
    - test/integration/**/*-steps.js
    extends: '@travi/react'
